# This is a basic workflow to help you get started with Actions
name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.0.0
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "masters-cs-yahoo-finance"
          heroku_email: ${{secrets.cgcadenas04@hotmail.com}}""
          buildpack: 'heroku/python'
          usedocker: false
